# Copyright (C) 2024 Ningqi Wang (0xf3cd) <https://github.com/0xf3cd>

from datetime import date, datetime
from typing import Protocol, runtime_checkable

from ..defines import Jieqi
from .dates import CalendarType, CalendarDate, JieqiTime


@runtime_checkable
class CalendarUtilsProtocol(Protocol):
  '''
  The protocol that all CalendarUtils classes conform to.

  The members are instance methods: the protocol describes "an object that offers these
  operations", which is what backends with per-instance state need to be (see issue #86;
  `CelestialCalendarUtils` is one instance per lunar algorithm).  The HKO backend is the one
  anomaly -- a module whose functions satisfy the protocol structurally at runtime but
  invisibly to mypy, so its resolver branch carries a `cast` (see `calendar_utils_of`).

  Implementations may differ only in the *precision* of `jieqi_moment`: a data source that
  publishes jieqi dates but not their moments can answer no better than midnight of that
  date (`hko_data_utils`), while one carrying the real moments answers to the second
  (`CelestialCalendarUtils`).  Everything else here is date-level and must agree, which is
  what makes conforming implementations substitutable for one another.

  Two methods ride on that precision and escape the "must agree" rule: `prev_jie`/`next_jie`
  name the jie bracketing a moment, so between midnight and the true moment of a jieqi day the
  two backends legitimately name different jie.  The divergence is moment-shaped, not noise
  (~1.6% of random moments, all landing on jieqi days), and it propagates: `BaziChart`'s da-yun
  start counts jie from birth, so a jieqi-day birth can shift it by a full da-yun step (~10
  years).  Date-level queries stay within the frozen parity whitelist instead (see
  `tests/calendar/celestial_parity_data.py`).
  '''
  def get_min_supported_date(self, date_type: CalendarType) -> CalendarDate: ...
  def get_max_supported_date(self, date_type: CalendarType) -> CalendarDate: ...
  def is_valid_solar_date(self, d: CalendarDate) -> bool: ...
  def is_valid_lunar_date(self, d: CalendarDate) -> bool: ...
  def is_valid_ganzhi_date(self, d: CalendarDate) -> bool: ...
  def is_valid(self, d: CalendarDate) -> bool: ...
  def days_counts_in_ganzhi_year(self, ganzhi_year: int) -> list[int]: ...
  def lunar_to_solar(self, lunar_date: CalendarDate) -> CalendarDate: ...
  def solar_to_lunar(self, solar_date: CalendarDate) -> CalendarDate: ...
  def ganzhi_to_solar(self, ganzhi_date: CalendarDate) -> CalendarDate: ...
  def solar_to_ganzhi(self, solar_date: CalendarDate) -> CalendarDate: ...
  def lunar_to_ganzhi(self, lunar_date: CalendarDate) -> CalendarDate: ...
  def ganzhi_to_lunar(self, ganzhi_date: CalendarDate) -> CalendarDate: ...
  def to_solar(self, d: date | CalendarDate) -> CalendarDate: ...
  def to_lunar(self, d: date | CalendarDate) -> CalendarDate: ...
  def to_ganzhi(self, d: date | CalendarDate) -> CalendarDate: ...
  def to_date(self, d: date | CalendarDate) -> date: ...
  def jieqi_date(self, solar_year: int, jieqi: Jieqi) -> date: ...
  def jieqi_moment(self, solar_year: int, jieqi: Jieqi) -> datetime: ...
  def supported_jie_boundaries(self) -> tuple[datetime, datetime]: ...
  def prev_jie(self, dt: datetime) -> JieqiTime: ...
  def next_jie(self, dt: datetime) -> JieqiTime: ...
