name: Workflow on Push - Run Partial Tests with pytest
  
on:
  push:
    branches: [ '**' ]

jobs:  
  test-on-ubuntu:  
    runs-on: ubuntu-latest
    strategy:  
      matrix:  
        python-version: ["3.9", "3.12"]  
  
    steps:  
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5 
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip  
          if [ -f Requirements.txt ]; then pip install -r Requirements.txt; fi  
      - name: Testing and linting
        run: |
          chmod +x ./run_tests.py
          ./run_tests.py -ep 3 # Not running slow and hkodata tests. But rerunning errorprone tests.
  
  test-on-macos:  
    runs-on: macos-latest
    strategy:  
      matrix:  
        python-version: ["3.9", "3.12"]  
  
    steps:  
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5 
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip  
          if [ -f Requirements.txt ]; then pip install -r Requirements.txt; fi  
      - name: Testing and linting
        run: |
          chmod +x ./run_tests.py
          ./run_tests.py -ep 3 # Not running slow and hkodata tests. But rerunning errorprone tests.

  test-on-windows:  
    runs-on: windows-latest
    strategy:  
      matrix:  
        python-version: ["3.9", "3.12"]  
  
    steps:  
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5 
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |  
          python -m pip install --upgrade pip  
          if [ -f Requirements.txt ]; then pip install -r Requirements.txt; fi  
      - name: Testing and linting
        run: |
          python ./run_tests.py -ep 3 # Not running slow and hkodata tests. But rerunning errorprone tests.
